#!/bin/bash

Scripts can be written for all kinds of interpreters — bash, tsch, zsh, or other shells, or for Perl, Python, and so on.

The "#!" combo is called a shebang by most Unix geeks. 
This is used by the shell to decide which interpreter to run the rest of the script.


#for running bash script
bash script.sh

#you can also make ur script file as executable
chmod 755 script.sh
